
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azurekeyvault-secproclass
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: "" # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: aks-kv123
    cloudName: "AzurePublicCloud" # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: mysql-db-password
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: 7083c9f3-3894-4397-b6a8-b1afe552c9cc # The tenant ID of the key vault
  secretObjects:
  - secretName: aks-secret
    type: Opaque
    data:
    - objectName: mysql-db-password
      key: dbpassword
