apiVersion: v1
kind: Service
metadata:
  name: backend-app-clusterip ## IMPORTANT - use this name in Front NGNIX App code
spec:
  selector:
    app: backend-app
  ports:
  - name: http
    port: 80
    targetPort: 80

